<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P59243" ignored="0" name="Test" tests="2" failures="2" timestamp="2019-12-20T10:31:33 JST" time="120.178" errors="0">
  <testcase name="totalValidation" time="120.135" classname="Practice.EcommerceTest">
    <failure type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException" message="The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: [/Users/geeta.khatri/AppiumFramework/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0] 
">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: [/Users/geeta.khatri/AppiumFramework/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0] 

at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:164)
at Practice.basic.startServer(basic.java:35)
at Practice.EcommerceTest.totalValidation(EcommerceTest.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 120003 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:129)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:151)
... 30 more
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- totalValidation -->
  <testcase name="totalValidation" time="120.157" classname="Practice.EcommerceTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Practice.basic.getScreenshot(basic.java:92)
at resources.Listeners.onTestFailure(Listeners.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- totalValidation -->
</testsuite> <!-- Test -->
